# Generated by Django 4.1.1 on 2022-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_active_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("READ", "READER"), ("WRITE", "WRITER")],
                max_length=20,
                null=True,
            ),
        ),
    ]
