# Generated by Django 4.1.1 on 2022-09-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="active",
        ),
    ]
