# Generated by Django 4.1.1 on 2022-09-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_variety",
                    models.CharField(
                        choices=[
                            ("Sports", "Sports"),
                            ("Politics", "Politics"),
                            ("Science and technology", "Science and Technology"),
                            ("History", "History"),
                            ("Others", "Others"),
                        ],
                        max_length=40,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News categories",
            },
        ),
    ]
