# Generated by Django 4.1.1 on 2022-09-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_rename_news_variety_newscategories_news_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newscategories",
            name="news_category",
            field=models.CharField(max_length=40),
        ),
    ]
