# Generated by Django 4.1.1 on 2022-10-10 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0006_alter_news_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("one", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("two", models.PositiveIntegerField(blank=True, default=0, null=True)),
                (
                    "three",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("four", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("five", models.PositiveIntegerField(blank=True, default=0, null=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="news.news",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["news"],
            },
        ),
    ]
